#!/usr/bin/env python3
"""
Create Multi-Agent Supervisor System

This script generates a complete multi-agent supervisor system with
configured worker agents.
"""

import argparse
import json
import os
from pathlib import Path
from typing import Optional, List, Dict


SUPERVISOR_TEMPLATE = '''"""
{supervisor_name} - Multi-Agent Supervisor System

Generated by create_supervisor.py
"""

import os
import json
from typing import TypedDict, Annotated, Sequence, Dict, Any
import operator

from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langgraph.graph import StateGraph, END
from databricks_langchain import ChatDatabricks
import mlflow

from supervisor_orchestrator import SupervisorOrchestrator, AgentConfig
{imports}


# Load configuration
CONFIG_FILE = "{config_file}"


def load_config():
    """Load agent configuration."""
    with open(CONFIG_FILE, 'r') as f:
        return json.load(f)


def create_supervisor():
    """Create and configure the supervisor."""

    # Create orchestrator from config
    orchestrator = SupervisorOrchestrator.from_config_file(
        CONFIG_FILE,
        verbose=True
    )

    # Register agent executors
{executor_registrations}

    # Build graph
    orchestrator.build()

    return orchestrator


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python {supervisor_name}.py <query>")
        print("\\nExample:")
        print('  python {supervisor_name}.py "What were Q4 sales?"')
        sys.exit(1)

    query = sys.argv[1]

    # Enable MLflow tracing
    mlflow.langchain.autolog()

    # Create supervisor
    print("Creating multi-agent supervisor...")
    supervisor = create_supervisor()

    # Execute query
    print(f"\\nQuery: {{query}}\\n")

    with mlflow.start_run():
        result = supervisor.invoke(query)

        # Print response
        print("\\nFinal Response:")
        print("=" * 60)
        print(result["final_response"])
        print("=" * 60)

        # Print routing info
        print(f"\\nRouted to: {{result.get('next_agent', 'unknown')}}")

        # Log to MLflow
        mlflow.log_param("query", query)
        mlflow.log_param("selected_agent", result.get("next_agent", "unknown"))
        mlflow.log_metric("num_messages", len(result["messages"]))

    print("\\n✓ Done!")
'''


CUSTOM_EXECUTOR_TEMPLATE = '''
def {agent_name}_executor(config: Dict[str, Any], query: str) -> str:
    """
    Custom executor for {agent_name}.

    Args:
        config: Agent configuration dict
        query: User query string

    Returns:
        Agent response string
    """
    # TODO: Implement your custom agent logic here
    # Example:
    # - Call external APIs
    # - Query databases
    # - Use ML models
    # - Combine multiple data sources

    try:
        # Your implementation here
        result = f"Custom agent {{config.get('name', 'unknown')}} processing: {{query}}"
        return result

    except Exception as e:
        return f"Error in {agent_name}: {{str(e)}}"
'''


def generate_config_file(
    output_dir: Path,
    config_name: str,
    agents: List[Dict[str, Any]],
    routing_strategy: str = "llm"
) -> Path:
    """Generate agent configuration JSON file."""

    config = {
        "agents": {},
        "supervisor": {
            "routing_strategy": routing_strategy,
            "enable_fallback": True,
            "default_agent": "general_agent",
            "max_iterations": 10
        }
    }

    # Add agents to config
    for agent in agents:
        agent_name = agent["name"]
        config["agents"][agent_name] = {
            "type": agent["type"],
            "description": agent["description"],
            "config": agent.get("config", {}),
            "enabled": agent.get("enabled", True)
        }

        # Add keywords for rule-based routing
        if "keywords" in agent:
            config["agents"][agent_name]["config"]["keywords"] = agent["keywords"]

    # Write config file
    config_file = output_dir / f"{config_name}_config.json"
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

    print(f"✓ Generated config: {config_file}")
    return config_file


def generate_supervisor_file(
    output_dir: Path,
    supervisor_name: str,
    config_file: Path,
    agents: List[Dict[str, Any]]
) -> Path:
    """Generate supervisor implementation file."""

    # Determine required imports
    imports = []
    executor_registrations = []

    agent_types = set(agent["type"] for agent in agents)

    if "genie" in agent_types:
        imports.append("from supervisor_orchestrator import genie_agent_executor")
    if "rag" in agent_types:
        imports.append("from supervisor_orchestrator import rag_agent_executor")
    if "llm" in agent_types:
        imports.append("from supervisor_orchestrator import llm_agent_executor")

    # Generate executor registrations
    for agent in agents:
        agent_name = agent["name"]
        agent_type = agent["type"]

        if agent_type == "genie":
            executor_registrations.append(
                f'    orchestrator.register_agent_executor("{agent_name}", genie_agent_executor)'
            )
        elif agent_type == "rag":
            executor_registrations.append(
                f'    orchestrator.register_agent_executor("{agent_name}", rag_agent_executor)'
            )
        elif agent_type == "llm":
            executor_registrations.append(
                f'    orchestrator.register_agent_executor("{agent_name}", llm_agent_executor)'
            )
        elif agent_type == "custom":
            imports.append(f"from custom_executors import {agent_name}_executor")
            executor_registrations.append(
                f'    orchestrator.register_agent_executor("{agent_name}", {agent_name}_executor)'
            )

    # Format template
    imports_str = "\n".join(imports) if imports else ""
    registrations_str = "\n".join(executor_registrations)

    content = SUPERVISOR_TEMPLATE.format(
        supervisor_name=supervisor_name,
        config_file=config_file.name,
        imports=imports_str,
        executor_registrations=registrations_str
    )

    # Write supervisor file
    supervisor_file = output_dir / f"{supervisor_name}.py"
    with open(supervisor_file, 'w') as f:
        f.write(content)

    print(f"✓ Generated supervisor: {supervisor_file}")
    return supervisor_file


def generate_custom_executors(
    output_dir: Path,
    agents: List[Dict[str, Any]]
) -> Optional[Path]:
    """Generate custom executor template file."""

    custom_agents = [agent for agent in agents if agent["type"] == "custom"]

    if not custom_agents:
        return None

    # Generate custom executors file
    executors_content = [
        '"""',
        'Custom Agent Executors',
        '',
        'Implement your custom agent logic here.',
        '"""',
        '',
        'from typing import Dict, Any',
        ''
    ]

    for agent in custom_agents:
        executor_code = CUSTOM_EXECUTOR_TEMPLATE.format(agent_name=agent["name"])
        executors_content.append(executor_code)

    executors_file = output_dir / "custom_executors.py"
    with open(executors_file, 'w') as f:
        f.write('\n'.join(executors_content))

    print(f"✓ Generated custom executors: {executors_file}")
    return executors_file


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate multi-agent supervisor system"
    )
    parser.add_argument(
        "supervisor_name",
        help="Name of the supervisor system"
    )
    parser.add_argument(
        "--config",
        required=True,
        help="Path to JSON file with agent definitions"
    )
    parser.add_argument(
        "--routing",
        choices=["llm", "rules"],
        default="llm",
        help="Routing strategy (default: llm)"
    )
    parser.add_argument(
        "-o", "--output",
        default=".",
        help="Output directory"
    )

    args = parser.parse_args()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load agent definitions
    print(f"Loading agent definitions from: {args.config}")
    with open(args.config, 'r') as f:
        agent_defs = json.load(f)

    agents = agent_defs.get("agents", [])

    if not agents:
        print("Error: No agents defined in config file")
        sys.exit(1)

    print(f"Found {len(agents)} agent(s)")

    # Generate files
    print("\nGenerating files...")

    # 1. Generate config file
    config_file = generate_config_file(
        output_dir,
        args.supervisor_name,
        agents,
        args.routing
    )

    # 2. Generate supervisor file
    supervisor_file = generate_supervisor_file(
        output_dir,
        args.supervisor_name,
        config_file,
        agents
    )

    # 3. Generate custom executors if needed
    executors_file = generate_custom_executors(output_dir, agents)

    # Print summary
    print(f"\n✓ Supervisor system generated successfully!")
    print(f"\nFiles created:")
    print(f"  - Configuration: {config_file}")
    print(f"  - Supervisor: {supervisor_file}")
    if executors_file:
        print(f"  - Custom executors: {executors_file}")

    print(f"\nNext steps:")
    print(f"1. Review and customize configuration: {config_file}")
    if executors_file:
        print(f"2. Implement custom agent logic in: {executors_file}")
    print(f"3. Set environment variables:")
    print(f"   export DATABRICKS_HOST=https://your-workspace.cloud.databricks.com")
    print(f"   export DATABRICKS_TOKEN=dapi...")
    print(f"   export DATABRICKS_LLM_ENDPOINT=databricks-meta-llama-3-1-70b-instruct")
    print(f"4. Run the supervisor:")
    print(f'   python {supervisor_file} "Your question here"')


if __name__ == "__main__":
    main()
